version: '3.7'
services:
    fieldsets-logger:
        image: ${CONTAINER_REGISTRY:-fieldsets}/docker-logger:${LOGGER_VERSION:-latest}
        build:
            context: ./
            dockerfile: ${LOGGER_CONFIG_PATH:-./}Dockerfile
            args:
                LOGGER_VERSION: ${LOGGER_VERSION:-latest}
        container_name: fieldsets-logger
        hostname: fieldsets-logger
        ports:
            - ${LOGGER_PORT:-24224}:${LOGGER_PORT:-24224}
            - ${LOGGER_PORT:-24224}:${LOGGER_PORT:-24224}/udp
        environment:
            LOGGER_HOST: ${LOGGER_HOST:-172.28.0.2}
            LOGGER_PORT: ${LOGGER_PORT:-24224}
            LOGGER_LEVEL: ${LOGGER_LEVEL:-info}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fieldsets}
            POSTGRES_HOST: ${POSTGRES_HOST:-172.28.0.7}
            POSTGRES_DB: ${POSTGRES_DB:-fieldsets}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            PGOPTIONS: "-c search_path=pipeline"
            ENABLE_DEBUG_MODE: ${ENABLE_DEBUG_MODE:-true}
            ENABLE_LOGGING: ${ENABLE_LOGGING:-false} # Write logs to DB
        restart: on-failure
        volumes:
            - ${LOGGER_CONFIG_PATH:-./}fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
            - ${LOGGER_CONFIG_PATH:-./}parsers.conf:/fluent-bit/etc/parsers.conf
